### ISSUE TITLE
ODRC: Opslagvoorziening voor de publicaties

### ISSUE THREAD

**Issue by RutgerICATT** [GPP-Woo/GPP-publicatiebank#1]
**Description (why)**
uit PSA: Gestart kan worden met het realiseren van de back-end, door het ODRC in de basis neer te zetten. 
Dit vergt om te beginnen een opslagvoorziening voor de publicaties bestaande uit metadata 
(database) en documenten / bestanden. Bij het inrichten van de data-opslag kan al rekening 
gehouden worden met toekomstige epics inzake het model-beheer32. Ook is het raadzaam om gelijk 
rekening te houden met standaarden als TOOI en MDTO. Ook dienen loggegevens opgeslagen te 
kunnen worden.

**Acceptance criteria (what)**

**Specific details (how)**

**Test plan**

**Tasks**

- [x] #16
- [x] #18
- [x] #14
- [ ] #2

**Comment by sergei-maertens** [comment]
Considerations for estimate, based on initial data models information available.

* Figure out which models and attributes are relevant - probably best to approach this from the DiWoo sitemap definition to at least capture the required fields. For this research alone I'd need at least a day to better inform this ticket.
    - Informatieobject: central model holding the metadata + content of a document
    - Government Organisation: will be required to model the municipality doing the publishing
    - Publication: keep track of which documents are part of a single publication and whether something is published
    - Audit trails: who published what and when

* Integration of value lists ("waardelijsten"), docs: https://standaarden.overheid.nl/tooi/doc/tooi-waardelijsten/, actual lists: https://standaarden.overheid.nl/tooi/waardelijsten/. Might need some import-functionality, or can/should we query them live on the web somewhere? How to deal with their versioning? -> going to need a lot more research

* The value lists define document types, but there doesn't seem to be much overlap between ZGW API's Catalogi API. So we will need to figure out if we can re-use the Documenten API or not.

**Comment by sergei-maertens** [comment]
With the above in mind, I'm going to add at least a task list so we can split up chunks of work to get a grip on things.
