### ISSUE TITLE
ODRC: autorisatiegroepen inrichten

### ISSUE THREAD

**Issue by MarcoKlerks** [GPP-Woo/GPP-publicatiebank#145]
**Acceptatie criteria**

- Standaard zitten in het ODRC de volgende autorisatiegroepen ('Accounts' > 'Groepen')
   - Groep `Superuser`; gebruikers in deze groep mogen alles.
   - Groep `Technisch beheer`; gebruikers in deze groep mogen:
      - Alles zien.
      - Configuraties wijzigingen doorvoeren die zo nu en dan nodig zijn, met name Publicaties, Metadata, Accounts, API access, Certificaten, Services.
   - Groep `Functioneel beheer`; gebruikers in deze groep mogen:
      - Publicaties en Metadata wijzigen.
      -  Accounts, Logging en Handige links zien.

**Taken**

- [x] Configure groups in local dev environment
- [x] Add script to dump the groups (copy https://github.com/open-formulieren/open-forms/blob/master/bin/generate_default_groups_fixture.sh)
- [x] Add post-migrate signal to load the default groups (copy https://github.com/open-formulieren/open-forms/blob/f67892155c7638950947b794e754724e364db212/src/openforms/accounts/apps.py#L44)

**Comment by sergei-maertens** [comment]
Superusers in groepen (voor permissies) kan niet, dit is een checkbox op de individuele gebruiker (die ook via de OpenID login gezet wordt)

**Comment by MarcoKlerks** [comment]
> Superusers in groepen (voor permissies) kan niet, dit is een checkbox op de individuele gebruiker (die ook via de OpenID login gezet wordt)

Ah ja, ik zie het! Kan de groep "Superuser" dan verwijderd worden om verwarring te voorkomen?

**Comment by sergei-maertens** [comment]
> > Superusers in groepen (voor permissies) kan niet, dit is een checkbox op de individuele gebruiker (die ook via de OpenID login gezet wordt)
> 
> Ah ja, ik zie het! Kan de groep "Superuser" dan verwijderd worden om verwarring te voorkomen?

Zeker - in de fixture zitten nu enkel de "Technisch beheer" en "Functioneel beheer" groepen. Ik gooi hem weg op de testomgeving.
