### ISSUE TITLE
ODRC: Offer file to Search

### ISSUE THREAD

**Issue by MarcoKlerks** [GPP-Woo/GPP-publicatiebank#151]
[ODRC #149](https://github.com/GeneriekPublicatiePlatformWoo/registratie-component/issues/149) en [Search #12](https://github.com/GeneriekPublicatiePlatformWoo/search/issues/12) zijn randvoorwaardelijk!

**Acceptatie criteria**

- Bij de creatie van een *document*  wordt ook het bestand meegestuurd naar de Search API voor indexering,
- Dit werkt zowel bij handelingen via de ODRC API als bij handelingen via de admin-interface.

Noot: Het bestand kan bij een documentregistratie later niet meer gewijzigd worden. Als het bestand gewijizgd moet worden, dan moet een nieuwe registratie aangemaakt worden en moet de oude registratie ingetrokken worden.

**Taken**

- [ ]

**Comment by sergei-maertens** [comment]
@MarcoKlerks considering the support for large files and the webserver configuration (typically) only allowing uploads of max 4GB, this push approach seems not recommended. Instead, we feel it's better to change this into a pull model where GPP-Search will download the file and then index it.

So I would propose to move this user story to GPP-Zoeken instead and rephrase it. For that reason, we're waiting with an estimate.

**Comment by MarcoKlerks** [comment]
@sergei-maertens I've altered [Search #10](https://github.com/GPP-Woo/GPP-zoeken/issues/10) and Search [#12](https://github.com/GPP-Woo/GPP-zoeken/issues/12) as requested. I assume we don't need any changes to the ODRC / Woo-publicatiebank anymore, so I can close ("as not planned") this story?
