### ISSUE TITLE
ODRC: Add missing filter parameters to documents API

### ISSUE THREAD

**Issue by sergei-maertens** [GPP-Woo/GPP-publicatiebank#157]
Additional filters on top of what's requested in #73

These filter parameters are required for the sitemap generation in ODBP. They apply to the `/api/v1/documenten` endpoint.

**Filters to add**

- [x] `registratiedatumVanaf` & `registratiedatumTot` - same as for `Publicatie` resource
- [x] `creatiedatumVanaf` & `creatiedatumTot` - similar to `registratiedatum`, however this is a date field rather than datetime. Apply the same `less than` behaviour for consistency.
- [x] `laatstGewijzigdDatumVanaf` & `laatstGewijzigdDatumTot`: more of the same :)

This should provide sufficient flexibility for the ODBP to query the data efficiently for the site map generation

**Comment by felixcicatt** [comment]
@sergei-maertens volgens mij kan ik in de datumtijd filters geen tijdzone meegeven. Welke tijdzone wordt aangenomen, is dat de tijdzone van de server?

**Comment by sergei-maertens** [comment]
> @sergei-maertens volgens mij kan ik in de datumtijd filters geen tijdzone meegeven. Welke tijdzone wordt aangenomen, is dat de tijdzone van de server?

Je zou wel time zone informatie mee kunnen geven, in de unit tests zie ik ze op die manier terug. `+00:00` voor UTC, `+01:00` voor NL wintertijd.

Onder water is alles in UTC opgeslagen en worden offsets ook vertaald naar UTC voor queries

**Comment by felixcicatt** [comment]
De tijdzone werkt prima, ik moest alleen even netjes het `+` karakter escapen in de query parameter :-)
