### ISSUE TITLE
ODRC: verwijderen publicatie

### ISSUE THREAD

**Issue by RutgerICATT** [GPP-Woo/GPP-publicatiebank#7]
**Description (why)**
uit PSA: Bestaande (concept-)publicaties zullen ook verwijderd moeten kunnen worden. Het zal wenselijk zijn 
om zowel één publicatie als een lijst (array) aan publicaties te verwijderen. Het verwijderen van een 
of meerdere publicaties zal in de logging vastgelegd moeten worden.

**Acceptance criteria (what)**

**Specific details (how)**

**Test plan**

**Comment by sergei-maertens** [comment]
Important here:

* Delete is really gone from the database
* Create timeline log entry of this action with a representation of what was deleted (need detailed metadata in the log record)
* Make sure that any related files on disk are also removed
